n9999[0]=lan
n10000[0]=lan
n10001[0]=lan
n10002[0]=lan
client[0]=lan

n9999[image]="kathara/base"
n10000[image]="kathara/base"
n10001[image]="kathara/base"
n10002[image]="kathara/base"
client[image]="kathara/base"
