n9999[0]=lan_n9999
n10000[0]=lan_n10000
n10001[0]=lan_n10001
n10002[0]=lan_n10002
client[0]=lan_client
rtr[0]=lan_n9999
rtr[1]=lan_n10000
rtr[2]=lan_n10001
rtr[3]=lan_n10002
rtr[4]=lan_client

n9999[image]="kathara/base"
n10000[image]="kathara/base"
n10001[image]="kathara/base"
n10002[image]="kathara/base"
client[image]="kathara/base"
rtr[image]="kathara/base"
