services:
  node9999:
    environment:
      ENABLE_TC: "1"
      ACK: "1"
      METRICS_INTERVAL: "10s"
      BANDWIDTH_MBPS: "1000"
      TC_RULES: "10.0.0.10,2gbit,0.35ms;10.0.0.11,2gbit,0.45ms;10.0.0.12,2gbit,0.55ms"
    cpus: "0.80"
    mem_limit: 900m

  node10000:
    environment:
      ENABLE_TC: "1"
      ACK: "1"
      METRICS_INTERVAL: "10s"
      BANDWIDTH_MBPS: "1000"
      TC_RULES: "10.0.0.9,2gbit,0.35ms;10.0.0.11,2gbit,0.35ms;10.0.0.12,2gbit,0.45ms"
    cpus: "0.80"
    mem_limit: 900m

  node10001:
    environment:
      ENABLE_TC: "1"
      ACK: "1"
      METRICS_INTERVAL: "10s"
      BANDWIDTH_MBPS: "1000"
      TC_RULES: "10.0.0.9,2gbit,0.45ms;10.0.0.10,2gbit,0.35ms;10.0.0.12,2gbit,0.35ms"
    cpus: "0.80"
    mem_limit: 900m

  node10002:
    environment:
      ENABLE_TC: "1"
      ACK: "1"
      METRICS_INTERVAL: "10s"
      BANDWIDTH_MBPS: "1000"
      TC_RULES: "10.0.0.9,2gbit,0.55ms;10.0.0.10,2gbit,0.45ms;10.0.0.11,2gbit,0.35ms"
    cpus: "0.80"
    mem_limit: 900m

  # client:
  #   cpus: "0.30"
  #   mem_limit: 256m

  # prometheus:
  #   cpus: "0.15"
  #   mem_limit: 384m

  # grafana:
  #   cpus: "0.15"
  #   mem_limit: 384m
