// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: core/proto/server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Op int32

const (
	Op_PUT    Op = 0
	Op_GET    Op = 1
	Op_DELETE Op = 2
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "PUT",
		1: "GET",
		2: "DELETE",
	}
	Op_value = map[string]int32{
		"PUT":    0,
		"GET":    1,
		"DELETE": 2,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_server_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_core_proto_server_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_server_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_core_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_server_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_core_proto_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_core_proto_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_core_proto_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_server_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Op                     `protobuf:"varint,1,opt,name=op,proto3,enum=proto.Op" json:"op,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	VnodeId       uint32                 `protobuf:"varint,4,opt,name=vnode_id,json=vnodeId,proto3" json:"vnode_id,omitempty"`
	Version       uint64                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationRequest) Reset() {
	*x = ReplicationRequest{}
	mi := &file_core_proto_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationRequest) ProtoMessage() {}

func (x *ReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationRequest.ProtoReflect.Descriptor instead.
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_server_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicationRequest) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_PUT
}

func (x *ReplicationRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReplicationRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ReplicationRequest) GetVnodeId() uint32 {
	if x != nil {
		return x.VnodeId
	}
	return 0
}

func (x *ReplicationRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ReplicationBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*ReplicationRequest  `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationBatchRequest) Reset() {
	*x = ReplicationBatchRequest{}
	mi := &file_core_proto_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationBatchRequest) ProtoMessage() {}

func (x *ReplicationBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationBatchRequest.ProtoReflect.Descriptor instead.
func (*ReplicationBatchRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_server_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicationBatchRequest) GetRequests() []*ReplicationRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ClusterNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RpcAddr       string                 `protobuf:"bytes,2,opt,name=rpc_addr,json=rpcAddr,proto3" json:"rpc_addr,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterNode) Reset() {
	*x = ClusterNode{}
	mi := &file_core_proto_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterNode) ProtoMessage() {}

func (x *ClusterNode) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterNode.ProtoReflect.Descriptor instead.
func (*ClusterNode) Descriptor() ([]byte, []int) {
	return file_core_proto_server_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterNode) GetRpcAddr() string {
	if x != nil {
		return x.RpcAddr
	}
	return ""
}

func (x *ClusterNode) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ClusterVNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Primary       string                 `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"`
	Replicas      []string               `protobuf:"bytes,3,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterVNode) Reset() {
	*x = ClusterVNode{}
	mi := &file_core_proto_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterVNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterVNode) ProtoMessage() {}

func (x *ClusterVNode) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterVNode.ProtoReflect.Descriptor instead.
func (*ClusterVNode) Descriptor() ([]byte, []int) {
	return file_core_proto_server_proto_rawDescGZIP(), []int{7}
}

func (x *ClusterVNode) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClusterVNode) GetPrimary() string {
	if x != nil {
		return x.Primary
	}
	return ""
}

func (x *ClusterVNode) GetReplicas() []string {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type ClusterState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Nodes         []*ClusterNode         `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Vnodes        []*ClusterVNode        `protobuf:"bytes,3,rep,name=vnodes,proto3" json:"vnodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterState) Reset() {
	*x = ClusterState{}
	mi := &file_core_proto_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterState) ProtoMessage() {}

func (x *ClusterState) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterState.ProtoReflect.Descriptor instead.
func (*ClusterState) Descriptor() ([]byte, []int) {
	return file_core_proto_server_proto_rawDescGZIP(), []int{8}
}

func (x *ClusterState) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ClusterState) GetNodes() []*ClusterNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ClusterState) GetVnodes() []*ClusterVNode {
	if x != nil {
		return x.Vnodes
	}
	return nil
}

type StreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Op                     `protobuf:"varint,1,opt,name=op,proto3,enum=proto.Op" json:"op,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // Empty for GET and DELETE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamReq) Reset() {
	*x = StreamReq{}
	mi := &file_core_proto_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReq) ProtoMessage() {}

func (x *StreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReq.ProtoReflect.Descriptor instead.
func (*StreamReq) Descriptor() ([]byte, []int) {
	return file_core_proto_server_proto_rawDescGZIP(), []int{9}
}

func (x *StreamReq) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_PUT
}

func (x *StreamReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StreamReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type StreamResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Op                     `protobuf:"varint,1,opt,name=op,proto3,enum=proto.Op" json:"op,omitempty"` // So the client knows what is being answered
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`          // Only populated for GET
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResp) Reset() {
	*x = StreamResp{}
	mi := &file_core_proto_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResp) ProtoMessage() {}

func (x *StreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResp.ProtoReflect.Descriptor instead.
func (*StreamResp) Descriptor() ([]byte, []int) {
	return file_core_proto_server_proto_rawDescGZIP(), []int{10}
}

func (x *StreamResp) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_PUT
}

func (x *StreamResp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StreamResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// VNodeTransferReq initiates vnode snapshot transfer.
// Client sends metadata in first message, then receives streaming responses with data.
type VNodeTransferReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VnodeId        uint32                 `protobuf:"varint,1,opt,name=vnode_id,json=vnodeId,proto3" json:"vnode_id,omitempty"`                      // Vnode ID to transfer (0..1023)
	PlacementEpoch uint64                 `protobuf:"varint,2,opt,name=placement_epoch,json=placementEpoch,proto3" json:"placement_epoch,omitempty"` // Placement epoch for ordering; receiver ignores old epochs
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VNodeTransferReq) Reset() {
	*x = VNodeTransferReq{}
	mi := &file_core_proto_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VNodeTransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VNodeTransferReq) ProtoMessage() {}

func (x *VNodeTransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VNodeTransferReq.ProtoReflect.Descriptor instead.
func (*VNodeTransferReq) Descriptor() ([]byte, []int) {
	return file_core_proto_server_proto_rawDescGZIP(), []int{11}
}

func (x *VNodeTransferReq) GetVnodeId() uint32 {
	if x != nil {
		return x.VnodeId
	}
	return 0
}

func (x *VNodeTransferReq) GetPlacementEpoch() uint64 {
	if x != nil {
		return x.PlacementEpoch
	}
	return 0
}

// VNodeTransferResp streams snapshot entries from primary to replica.
// Large snapshots are chunked into multiple responses; receiver reassembles.
type VNodeTransferResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VnodeId        uint32                 `protobuf:"varint,1,opt,name=vnode_id,json=vnodeId,proto3" json:"vnode_id,omitempty"`                      // Echo of requested vnode ID
	PlacementEpoch uint64                 `protobuf:"varint,2,opt,name=placement_epoch,json=placementEpoch,proto3" json:"placement_epoch,omitempty"` // Replicate of request epoch
	// Snapshot entry: one (key, value, version) per response message.
	// End-of-stream indicated by empty_entries=true.
	Key           string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`                               // Write version for conflict detection during merge
	EmptyEntries  bool   `protobuf:"varint,6,opt,name=empty_entries,json=emptyEntries,proto3" json:"empty_entries,omitempty"` // true = end-of-stream for this vnode; no more entries
	Error         string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`                                    // Set on error; receiver should abort transfer
	Tombstone     bool   `protobuf:"varint,8,opt,name=tombstone,proto3" json:"tombstone,omitempty"`                           // true if entry is a delete marker
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VNodeTransferResp) Reset() {
	*x = VNodeTransferResp{}
	mi := &file_core_proto_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VNodeTransferResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VNodeTransferResp) ProtoMessage() {}

func (x *VNodeTransferResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VNodeTransferResp.ProtoReflect.Descriptor instead.
func (*VNodeTransferResp) Descriptor() ([]byte, []int) {
	return file_core_proto_server_proto_rawDescGZIP(), []int{12}
}

func (x *VNodeTransferResp) GetVnodeId() uint32 {
	if x != nil {
		return x.VnodeId
	}
	return 0
}

func (x *VNodeTransferResp) GetPlacementEpoch() uint64 {
	if x != nil {
		return x.PlacementEpoch
	}
	return 0
}

func (x *VNodeTransferResp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VNodeTransferResp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *VNodeTransferResp) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VNodeTransferResp) GetEmptyEntries() bool {
	if x != nil {
		return x.EmptyEntries
	}
	return false
}

func (x *VNodeTransferResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *VNodeTransferResp) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

var File_core_proto_server_proto protoreflect.FileDescriptor

const file_core_proto_server_proto_rawDesc = "" +
	"\n" +
	"\x17core/proto/server.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x8c\x01\n" +
	"\x12ReplicationRequest\x12\x19\n" +
	"\x02op\x18\x01 \x01(\x0e2\t.proto.OpR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x19\n" +
	"\bvnode_id\x18\x04 \x01(\rR\avnodeId\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\"P\n" +
	"\x17ReplicationBatchRequest\x125\n" +
	"\brequests\x18\x01 \x03(\v2\x19.proto.ReplicationRequestR\brequests\"N\n" +
	"\vClusterNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\brpc_addr\x18\x02 \x01(\tR\arpcAddr\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\"T\n" +
	"\fClusterVNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aprimary\x18\x02 \x01(\tR\aprimary\x12\x1a\n" +
	"\breplicas\x18\x03 \x03(\tR\breplicas\"{\n" +
	"\fClusterState\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12(\n" +
	"\x05nodes\x18\x02 \x03(\v2\x12.proto.ClusterNodeR\x05nodes\x12+\n" +
	"\x06vnodes\x18\x03 \x03(\v2\x13.proto.ClusterVNodeR\x06vnodes\"N\n" +
	"\tStreamReq\x12\x19\n" +
	"\x02op\x18\x01 \x01(\x0e2\t.proto.OpR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"S\n" +
	"\n" +
	"StreamResp\x12\x19\n" +
	"\x02op\x18\x01 \x01(\x0e2\t.proto.OpR\x02op\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"V\n" +
	"\x10VNodeTransferReq\x12\x19\n" +
	"\bvnode_id\x18\x01 \x01(\rR\avnodeId\x12'\n" +
	"\x0fplacement_epoch\x18\x02 \x01(\x04R\x0eplacementEpoch\"\xf2\x01\n" +
	"\x11VNodeTransferResp\x12\x19\n" +
	"\bvnode_id\x18\x01 \x01(\rR\avnodeId\x12'\n" +
	"\x0fplacement_epoch\x18\x02 \x01(\x04R\x0eplacementEpoch\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\x12#\n" +
	"\rempty_entries\x18\x06 \x01(\bR\femptyEntries\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x1c\n" +
	"\ttombstone\x18\b \x01(\bR\ttombstone*\"\n" +
	"\x02Op\x12\a\n" +
	"\x03PUT\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x022\xe3\x03\n" +
	"\x02KV\x12,\n" +
	"\x03Get\x12\x11.proto.GetRequest\x1a\x12.proto.GetResponse\x120\n" +
	"\x03Put\x12\x11.proto.PutRequest\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x06Delete\x12\x14.proto.DeleteRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\tReplicate\x12\x19.proto.ReplicationRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x0eReplicateBatch\x12\x1e.proto.ReplicationBatchRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\x0fGetClusterState\x12\x16.google.protobuf.Empty\x1a\x13.proto.ClusterState\x123\n" +
	"\bStreamKV\x12\x10.proto.StreamReq\x1a\x11.proto.StreamResp(\x010\x01\x12F\n" +
	"\rTransferVNode\x12\x17.proto.VNodeTransferReq\x1a\x18.proto.VNodeTransferResp(\x010\x01B*Z(github.com/AymenBenyoub/nawst/core/protob\x06proto3"

var (
	file_core_proto_server_proto_rawDescOnce sync.Once
	file_core_proto_server_proto_rawDescData []byte
)

func file_core_proto_server_proto_rawDescGZIP() []byte {
	file_core_proto_server_proto_rawDescOnce.Do(func() {
		file_core_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_server_proto_rawDesc), len(file_core_proto_server_proto_rawDesc)))
	})
	return file_core_proto_server_proto_rawDescData
}

var file_core_proto_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_core_proto_server_proto_goTypes = []any{
	(Op)(0),                         // 0: proto.Op
	(*GetRequest)(nil),              // 1: proto.GetRequest
	(*GetResponse)(nil),             // 2: proto.GetResponse
	(*PutRequest)(nil),              // 3: proto.PutRequest
	(*DeleteRequest)(nil),           // 4: proto.DeleteRequest
	(*ReplicationRequest)(nil),      // 5: proto.ReplicationRequest
	(*ReplicationBatchRequest)(nil), // 6: proto.ReplicationBatchRequest
	(*ClusterNode)(nil),             // 7: proto.ClusterNode
	(*ClusterVNode)(nil),            // 8: proto.ClusterVNode
	(*ClusterState)(nil),            // 9: proto.ClusterState
	(*StreamReq)(nil),               // 10: proto.StreamReq
	(*StreamResp)(nil),              // 11: proto.StreamResp
	(*VNodeTransferReq)(nil),        // 12: proto.VNodeTransferReq
	(*VNodeTransferResp)(nil),       // 13: proto.VNodeTransferResp
	(*emptypb.Empty)(nil),           // 14: google.protobuf.Empty
}
var file_core_proto_server_proto_depIdxs = []int32{
	0,  // 0: proto.ReplicationRequest.op:type_name -> proto.Op
	5,  // 1: proto.ReplicationBatchRequest.requests:type_name -> proto.ReplicationRequest
	7,  // 2: proto.ClusterState.nodes:type_name -> proto.ClusterNode
	8,  // 3: proto.ClusterState.vnodes:type_name -> proto.ClusterVNode
	0,  // 4: proto.StreamReq.op:type_name -> proto.Op
	0,  // 5: proto.StreamResp.op:type_name -> proto.Op
	1,  // 6: proto.KV.Get:input_type -> proto.GetRequest
	3,  // 7: proto.KV.Put:input_type -> proto.PutRequest
	4,  // 8: proto.KV.Delete:input_type -> proto.DeleteRequest
	5,  // 9: proto.KV.Replicate:input_type -> proto.ReplicationRequest
	6,  // 10: proto.KV.ReplicateBatch:input_type -> proto.ReplicationBatchRequest
	14, // 11: proto.KV.GetClusterState:input_type -> google.protobuf.Empty
	10, // 12: proto.KV.StreamKV:input_type -> proto.StreamReq
	12, // 13: proto.KV.TransferVNode:input_type -> proto.VNodeTransferReq
	2,  // 14: proto.KV.Get:output_type -> proto.GetResponse
	14, // 15: proto.KV.Put:output_type -> google.protobuf.Empty
	14, // 16: proto.KV.Delete:output_type -> google.protobuf.Empty
	14, // 17: proto.KV.Replicate:output_type -> google.protobuf.Empty
	14, // 18: proto.KV.ReplicateBatch:output_type -> google.protobuf.Empty
	9,  // 19: proto.KV.GetClusterState:output_type -> proto.ClusterState
	11, // 20: proto.KV.StreamKV:output_type -> proto.StreamResp
	13, // 21: proto.KV.TransferVNode:output_type -> proto.VNodeTransferResp
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_core_proto_server_proto_init() }
func file_core_proto_server_proto_init() {
	if File_core_proto_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_server_proto_rawDesc), len(file_core_proto_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_proto_server_proto_goTypes,
		DependencyIndexes: file_core_proto_server_proto_depIdxs,
		EnumInfos:         file_core_proto_server_proto_enumTypes,
		MessageInfos:      file_core_proto_server_proto_msgTypes,
	}.Build()
	File_core_proto_server_proto = out.File
	file_core_proto_server_proto_goTypes = nil
	file_core_proto_server_proto_depIdxs = nil
}
